spring:
  datasource:
    url: jdbc:mysql://localhost:3002/sharenotes_dev
    username: sharenotes
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always

client:
  origin: http://localhost:3000

# Logs sql statements
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
          EnumType: TRACE

