spring:
  datasource:
    url: jdbc:mysql://localhost:3003/sharenotes_test
    username: sharenotes
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
