spring:
  datasource:
    url: jdbc:mysql://localhost:3003/markdown_notebook_test
    username: markdown_notebook
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
