version: '3'

services:
  mysql-dev:
    image: mysql:5.7
    container_name: mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: markdown_notebook_dev
      MYSQL_USER: markdown_notebook
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
      - ./my.dev.cnf:/etc/mysql/conf.d/my.cnf
      - ./initdb.d:/docker-entrypoint-initdb.d
      - mysql_dev_data:/var/lib/mysql
    ports:
      - 3002:3306
    networks:
      - db_network

  mysql-test:
    image: mysql:5.7
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: markdown_notebook_test
      MYSQL_USER: markdown_notebook
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
      - ./my.test.cnf:/etc/mysql/conf.d/my.cnf
      - ./initdb.d:/docker-entrypoint-initdb.d
      - mysql_test_data:/var/lib/mysql
    ports:
      - 3003:3307
    networks:
      - db_network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOSTS=mysql-dev,mysql-test
      - PMA_PORTS=3306,3307
      - PMA_USER=markdown_notebook
      - PMA_PASSWORD=password
    ports:
      - 3004:80
    networks:
      - db_network

networks:
  db_network:

volumes:
  mysql_dev_data:
    driver: local
  mysql_test_data:
    driver: local
